### ISSUE TITLE
AttributeError: 'AstNode' object has no attribute 'getChilds'

### ISSUE THREAD

**Issue by yumouse** [JonathanSalwan/Tigress_protection#14]
I am sorry to trouble you again. The last AttributeError is figured out by using Triton dev-v0.8, but this time I met similar problem here.  I am using ubuntu 16.04 and it seems there are lots of problem like AttributeError, I guess it might caused by the dependencies such trion, z3 and others. 
**So could I ask about that what's the version of all these dependencies when you are doing experiments described in your paper.** We are trying to reproduce the results and do some researchs based on your code and paper, and I have to say that what you guys did are awesome for researchers like us focusing on de-obfuscation problem.
Hope that we can get your help! Thx in advance!
Here are specific problem we met this time:
Traceback (most recent call last):   File "./solve-vm.py", line 754, in <module>     retValue  = main()   File "./solve-vm.py", line 664, in main     M = generateLLVMExpressions(ctx, 0)   File "./solve-vm.py", line 617, in generateLLVMExpressions     e = tritonexprs2arybo(exprs)   File "/home/kuang/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 168, in tritonexprs2arybo     e = tritonast2arybo(e.getAst(), True, False, context)   File "/home/kuang/.local/lib/python2.7/site-packages/arybo/tools/triton_.py", line 31, in tritonast2arybo     children_ = e.getChilds() AttributeError: 'AstNode' object has no attribute 'getChilds'

**Comment by JonathanSalwan** [comment]
You have an old version of Arybo.

Below versions of deps:

* Triton (master or dev-v0.8)
* Arybo (master)
* z3 (4.8.0)
* Capstone (4.x)

**Comment by yumouse** [comment]
Thx!!!!!
