### ISSUE TITLE
llvmlite module unavailable! can't assemble to LLVM IR

### ISSUE THREAD

**Issue by deepsadhi** [JonathanSalwan/Tigress_protection#6]
I am trying to run following sample code using Docker.
```bash
$ ./solve-vm.py ./tigress-challenges/tigress-0-challenge-0
```

I used modified version of `Dockerfile` to build the docker image. It can be found in this [PR](https://github.com/JonathanSalwan/Tigress_protection/pull/5). Then I followed following steps to run the sample code inside Docker container
```bash
$ docker run -v /home/deeps/Research/tools/Tigress_protection:/tigress_protection -ti --name=tp --ulimit='stack=-1:-1' itp 
$ cd /tigress_protection/
$ ./solve-vm.py tigress-challenges/tigress-0-challenge-0 
```  
I encountered following error while executing the sample code
```bash
root@05f8a75263da:/tigress_protection/tools/tp# ./solve-vm.py tigress-challenges/tigress-0-challenge-0 
[+] Loading 0x400040 - 0x400238
[+] Loading 0x400238 - 0x400254
[+] Loading 0x400000 - 0x400f14
[+] Loading 0x601e28 - 0x602550
[+] Loading 0x601e50 - 0x601fe0
[+] Loading 0x400254 - 0x400298
[+] Loading 0x400dc4 - 0x400e08
[+] Loading 0x000000 - 0x000000
[+] Loading 0x601e28 - 0x602000
[+] Hooking printf
[+] Hooking __libc_start_main
[+] Hooking strtoul
[+] Starting emulation.
[+] __libc_start_main hooked
[+] argv[0] = tigress-challenges/tigress-0-challenge-0
[+] argv[1] = 1234
[+] strtoul hooked
[+] Symbolizing the strtoul return
[+] printf hooked
3035321144166078008
[+] Slicing end-point user expression
[-] Instruction not supported: 0x400539: hlt
[+] Instruction executed: 39816
[+] Unique instruction executed: 458
[+] PC len: 0
[+] Emulation done.
[+] Generating symbolic_expressions/tigress-0-challenge-0.py
[+] Converting symbolic expressions to an LLVM module...
Traceback (most recent call last):
  File "./solve-vm.py", line 760, in <module>
    retValue  = main()
  File "./solve-vm.py", line 670, in main
    M = generateLLVMExpressions(ctx, 0)
  File "./solve-vm.py", line 625, in generateLLVMExpressions
    M = to_llvm_function(e,[var.v])
  File "/usr/local/lib/python2.7/dist-packages/arybo/lib/exprs_asm.py", line 201, in to_llvm_function
    raise RuntimeError("llvmlite module unavailable! can't assemble to LLVM IR...")
RuntimeError: llvmlite module unavailable! can't assemble to LLVM IR...
```

**Comment by JonathanSalwan** [comment]
Try to install [llvmlite-0.16.0.tar.gz](https://github.com/JonathanSalwan/Tigress_protection/files/2842373/llvmlite-0.16.0.tar.gz)

**Comment by deepsadhi** [comment]
Thanks installed using `pip`.
