### ISSUE TITLE
AttributeError: 'long' objects has no attribute 'rol'

### ISSUE THREAD

**Issue by vDunning** [JonathanSalwan/Tigress_protection#9]
I am trying to reproduce results using the `solve-vm.py` script. 

I am running on Linux (Manjaro 4.19.32-1-MANJARO) inside the docker image. I manually reinstalled arybo by cloning the repository and running `python setup.py install` inside the folder.

When runing the script with `sample15-unprotected.bin` I get the following error:

```
[+] Loading 0x400040 - 0x400238
[+] Loading 0x400238 - 0x400254
[+] Loading 0x400000 - 0x4009ec
[+] Loading 0x600e10 - 0x601048
[+] Loading 0x600e28 - 0x600ff8
[+] Loading 0x400254 - 0x400274
[+] Loading 0x400850 - 0x40089c
[+] Loading 0x000000 - 0x000000
[+] Loading 0x600e10 - 0x601000
[+] Hooking puts
[+] Hooking printf
[+] Hooking __libc_start_main
[+] Hooking strtoul
[+] Starting emulation.
[+] __libc_start_main hooked
[+] argv[0] = ./samples/sample15-unprotected.bin
[+] argv[1] = 1234
[+] strtoul hooked
[+] Symbolizing the strtoul return
[+] printf hooked
140691328966713419
[+] Slicing end-point user expression
[-] Instruction not supported: 0x4004c9: hlt
[+] Instruction executed: 92
[+] Unique instruction executed: 90
[+] PC len: 0
[+] Emulation done.
[+] Generating symbolic_expressions/sample15-unprotected.bin.py
[+] Converting symbolic expressions to an LLVM module...
Traceback (most recent call last):
  File "./solve-vm.py", line 760, in <module>
    retValue  = main()
  File "./solve-vm.py", line 670, in main
    M = generateLLVMExpressions(ctx, 0)
  File "./solve-vm.py", line 623, in generateLLVMExpressions
    e = tritonexprs2arybo(exprs)
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 161, in tritonexprs2arybo
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 131, in tritonast2arybo
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 32, in <genexpr>
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 131, in tritonast2arybo
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 32, in <genexpr>
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 99, in tritonast2arybo
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 32, in <genexpr>
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 131, in tritonast2arybo
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 32, in <genexpr>
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 100, in tritonast2arybo
  File "build/bdist.linux-x86_64/egg/arybo/tools/triton_.py", line 93, in <lambda>
AttributeError: 'long' object has no attribute 'rol'
```
I am thinking this is caused by a mismatch in library versions but can not seem to figure out the right set of versions. Did you perhaps encounter similar problems?

Thanks in advance,

Vincent

**Comment by CoolTomatos** [comment]
Try using Triton from the master branch. Worked for me.

**Comment by CoolTomatos** [comment]
Should be fixed by #11
